### ISSUE TITLE
Quality app: Support validation of other resource types than DatasetMetadata

### ISSUE THREAD

**Issue by MrSnyder** [mrmap-community/mrmap#145]
### Environment
* Python version: 3.7+
* MrMap version:  1.0-pre

### Proposed Functionality

The functionality implemented by #129 should also be available for:

- Service (WMS, WFS, CSW)
- Layer (as WMS)
- Feature Type (as WFS)
- Service Metadata (ISO 19139)
- Layer Metadata (ISO 19139)
- Feature Type Metadata (ISO 19139)

### Use Case

User wants to perform an ETF-based validation of a registered WMS instance.

### Database Changes

~~Probably we need to provide a type hierarchy for `ConformityCheckRun`, one type for every validatable resource type. It's preferred not to use generic foreign keys here, so the propagation works.~~

~~This can be used as a test case for [Django Polymorphic](https://django-polymorphic.readthedocs.io/en/stable/)~~

We will add individual FKs in the `ConformityCheckRun` model to solve the polymorphic FK issue. See discussion #165 for details.

### External Dependencies
~~[Django Polymorphic](https://django-polymorphic.readthedocs.io/en/stable/)~~

### Tasks

- [x] Make ETF tests work with other resource types
- [x] Make internal tests work with other resource types
- [x] Adapt `ConformityCheckRun`: Add Fks to other resource types
- [x] Make sure that starting of checks from DatasetMetadata list view still works
- [x] Add possibility for starting checks from other resource list views
