### ISSUE TITLE
MapContext: Repair / Redo MapContext Create View

### ISSUE THREAD

**Issue by Unraveler** [mrmap-community/mrmap#164]
### Proposed Changes
Fix the MapContextCreateView and add more form fields when creating a new map context

### Justification
When creating a new map context, only the map context layers are created. There is no information for the MapContext table (title, abstract,...).
Also, there is yet no way to write title or abstract for the map context (or any other relevant information, just the layers)

### Story Points
@Unraveler : 5SP
@MrSnyder : 5SP

### Tasks

- [x] In MapContextCreateView create both MapContext instance and MapContextLayer instances
- [x] Use CreateSecured View Mixin if possible. If not then check for another solution in some similar problem foloowing the code base
- [x] Add new form fields to MapContextCreateView
